# .github/workflows/airtable_sync.yml
name: Sync Airtable → JSON et déploiement

on:
  schedule:
    - cron: '0 2 * * *'        # every day 02:00 UTC
  push:
    branches: [ main ]          # run on commits to main
  workflow_dispatch:            # allow manual run

permissions:
  contents: write               # allow pushing to the repo

concurrency:
  group: airtable-sync-${{ github.ref }}
  cancel-in-progress: true      # skip overlapping runs

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20        # Node ≥18 has global fetch
        cache: 'yarn'
        cache-dependency-path: batches/yarn.lock

    - name: Install dependencies
      run: |
        cd batches
        yarn install

    - name: Fetch Airtable & create JSON
      env:
        AIRTABLE_API_KEY:  ${{ secrets.AIRTABLE_API_KEY }}
        AIRTABLE_BASE_ID:  ${{ secrets.AIRTABLE_BASE_ID }}
        AIRTABLE_TABLE:    ${{ secrets.AIRTABLE_TABLE_NAME }}
      run: |
        node - <<'EOF'
        import fs from 'node:fs';
        import { mkdirSync } from 'node:fs';

        const apiKey   = process.env.AIRTABLE_API_KEY;
        const baseId   = process.env.AIRTABLE_BASE_ID;
        const table    = encodeURIComponent(process.env.AIRTABLE_TABLE);
        const headers  = { Authorization: `Bearer ${apiKey}` };

        async function fetchAll() {
          let url = `https://api.airtable.com/v0/${baseId}/${table}?pageSize=100`;
          let all = [];

          while (url) {
            const res = await fetch(url, { headers });
            if (!res.ok) throw new Error(`HTTP ${res.status}: ${await res.text()}`);
            const body = await res.json();
            all.push(...body.records.map(r => r.fields));
            url = body.offset ? `${url.split('?')[0]}?pageSize=100&offset=${body.offset}` : null;
          }
          return all;
        }

        (async () => {
          const records = await fetchAll();
          mkdirSync('batches/public', { recursive: true });
          fs.writeFileSync('batches/public/airtable.json', JSON.stringify(records, null, 2));
          console.log(`✅ Wrote ${records.length} records to batches/public/airtable.json`);
        })().catch(e => { console.error(e); process.exit(1); });
        EOF

    - name: Build app
      run: |
        cd batches
        yarn build

    - name: Copy build to docs directory
      run: |
        mkdir -p docs
        cp -r batches/out/* docs/
        touch docs/.nojekyll  # Prévient le traitement Jekyll sur GitHub Pages

    - name: Commit & push if changed
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name  "github-actions"
        git config --global user.email "github-actions@github.com"
        git add batches/public/airtable.json docs
        timestamp=$(date -u '+%Y-%m-%dT%H:%M:%SZ')
        git diff --staged --quiet || \
          (git commit -m "chore: update Airtable JSON et déploiement (${timestamp})" && \
           git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:${{ github.ref_name }})
